## Numpy ia a liabrary that allows us to work with arrays and matrices

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## Creating a 2D array

In [ ]:
c = np.array([[1,3,5],[2,4,6]])
print(c)

[[1 3 5]
 [2 4 6]]


## Creating a 3D array

In [ ]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Methods of array

In [ ]:
#creating an array with a specific data type
print(a.dtype)

int64


In [11]:
#to get the number of dimensions of an array
print(c.ndim)

2


In [12]:
#to get the shape of an array
print(c.shape)

(2, 3)


In [13]:
#range of numbers
print(np.arange(10))
print(np.arange(2,11))
print(np.arange(2,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [ ]:
np.random.randint(10,30)

15

In [19]:
np.random.randint(10,30, size=(3,3))

array([[19, 22, 15],
       [23, 20, 19],
       [10, 13, 29]], dtype=int32)

In [20]:
x= np.array([[7,2,3],[2,5,2],[3,5,1]])
y= np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)


[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [24]:
#matrix multiplication
print(x*y)

print(x@y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]
[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [22]:
print(x.dot(y))

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
print(np.dot(x,y))


[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [26]:
x.prod()

np.int64(12600)

In [27]:
x.mean()

np.float64(3.3333333333333335)

In [28]:
#mean of each column
x.mean(axis=0)

array([4., 4., 2.])

In [29]:
#mean of each row
x.mean(axis=1)

array([4., 3., 3.])

In [30]:
#functions of array
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [31]:
z= np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z,25)) #25th percentile
print(np.percentile(z,50)) #50th percentile 
print(np.percentile(z,75)) #75th percentile

3.0
5.0
7.0


In [35]:
arr= np.random.randint(10,50, size=(4,4))
print(arr)

[[27 26 49 40]
 [41 46 45 25]
 [48 27 24 34]
 [19 45 16 25]]


In [37]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[27 26]
 [49 40]
 [41 46]
 [45 25]
 [48 27]
 [24 34]
 [19 45]
 [16 25]]


In [39]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[27 26 49 40 41 46 45 25]
 [48 27 24 34 19 45 16 25]]


In [41]:
print(x[0]) #first row
print(x[1]) #second row

[7 2 3]
[2 5 2]


In [42]:
print(x[0,0]) #first row first element

7


In [43]:
print(x[0,1]) #first row second element

2


In [45]:
print(x[1,1]) #second row first element

5
